public with sharing class Foo {
    private String field_name;
    public Foo() {
    }

    public void BadlyNamedMethod() {
    }

    global void globalMethod() {
    }

    global void AnotherBadlyNamed() {
    }

    global void YetAnotherBadlyNamed() {
    }

    private String BadFieldName;
    private String BadFieldName2;
    private String BadFieldName3;
    private String BadFieldName4;

}
