name: Analyse Source Code
on: [push]

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PMD
        uses: rody/pmd-github-action@main
        id: pmd
        with:
          rulesets: 'rulesets/apex/quickstart.xml'
          reportfile: 'pmd-report.json'
          format: 'json'
      - name: PMD annotations
        uses: rody/pmd-annotations-github-action@main
        id: pmd-annotations
        with:
          reportfile: 'pmd-report.json'
