name: Pull Request Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analysis:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: PMD
        uses: rody/pmd-github-action@main
        with:
          rulesets: 'rulesets/apex/quickstart.xml'
          reportfile: 'pmd-report.json'
          format: 'json'
          failOnViolation: 'false'
      - name: Create Review from PMD report
        uses: rody/pmd-review-github-action@wip
        with:
          reportfile: 'pmd-report.json'
          pr-number: ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
